### ISSUE TITLE
Rehash on every run

### ISSUE THREAD

**Issue by andrewfraley** [Sliim/puppet-pyenv#5]
On every run it's doing  exec { "pyenv::rehash ${user} ${python}":

```
  pyenv::compile { "compile python ${version} for ${user}":
    user   => 'pyuser',
    python => '2.7.9',
    global => true,
  }
```

> Run bash command `pyenv rehash`
> Notice: /Stage[main]/Profile_python::Pyenv/Pyenv::Compile[compile python 2.7.9 for pyuser]/Exec[pyenv::rehash pyuser 2.7.9]/returns: executed successfully

**Comment by Sliim** [comment]
Hi!

Sorry I no longer use Puppet and do not maintain my module..
If you know a fix for this do not hesitate to submit a PR, I will review it and release a new version of this module. Maybe saying to run `pyenv::rehash` after `pyenv::compile` instead of running `pyenv::compile` before `pyenv::rehash` will resolve the issue.. but I can't test now.

Thanks for your feedback :)
